version: "3.9"
services:
  nextjs-grpc-infra:
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      GH_TOKEN: ${GH_TOKEN}
    volumes:
      - type: volume
        source: vscode-server-extensions
        target: /home/terraform/.vscode-server/extensions
      - type: volume
        source: vscode-server-insiders-extensions
        target: /home/terraform/.vscode-server-insiders/extensions
      - type: volume
        source: go
        target: /go
      - type: bind
        source: ../.certs/intermediate/ca.crt
        target: /etc/ssl/certs/root.crt
        read_only: true
        # These depends on the host system
      - type: bind
        source: ~/.aws/credentials
        target: /home/terraform/.aws/credentials
        read_only: true
      - type: bind
        source: ~/.kube
        target: /home/terraform/.kube

volumes:
  vscode-server-extensions:
    name: nextjs-grpc-infra-vscode-server-extensions
  vscode-server-insiders-extensions:
    name: nextjs-grpc-infra-vscode-server-insiders-extensions
  go:
    name: nextjs-grpc-infra-go
